services:
  - type: web
    name: mybudget-backend
    env: java
    plan: free
    branch: backend-dev
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: PORT
        value: 8080